site_name: Yszm's blog
theme:
  name: material            # 启用 Material 主题
  logo: assets/Logo.png
  language: zh              # 强制设为中文
  custom_dir: overrides
  features:
    - content.code.copy     # 复制代码按钮
    - navigation.top        # 返回顶部按钮
    - navigation.tabs       # 变成顶部导航栏
  palette:
    # 方案 1: 日间模式 (点击太阳切换)
    - scheme: default
      primary: teal         # 顶部颜色：深青色
      accent: purple        # 链接/按钮颜色：紫色
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # 方案 2: 夜间模式 (点击月亮切换)
    - scheme: slate         # "黑夜模式"
      primary: black        # 顶部变黑
      accent: lime          # 重点色变成醒目的青柠色
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.tasklist:      # 开启复选框功能
      custom_checkbox: true
  - pymdownx.highlight:     # 开启代码高亮
  - pymdownx.superfences:   # 让代码块更稳定（解决嵌套问题）
  - pymdownx.arithmatex:    # 开启数学公式
      generic: true

extra_javascript:
  - javascripts/mathjax.js  # 引入数学公式的js库
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - encryptcontent

nav:
  - 首页: index.md
  - 博客指南: guide.md
  - 建站心得: build_blog.md
  - 个人笔记:
      - 计算机视觉:
          - 数据集划分: cv/Split_datasets.md
          - 图像分类: cv/Image_Classification.md
          - 检验模型: cv/Predict_img.md
          - 策略: strategy.md
          - 对比性能: cv/Compare_model.md
          - 实战:
              - resnet18_CIFAR10: cv/exercises/resnet18_CIFAR10.md
              - resnet34_CIFAR100: cv/exercises/resnet34_CIFAR100.md
              - resnet50_Inter_Image_Classification: cv/exercises/resnet50_Inter_Image_Classification.md
              - resnet50_Cassava_Leaf_Disease_Classification: cv/exercises/resnet50_Cassava_Leaf_Disease_Classification.md